// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvl9Zjv7Io3Yen-M-w9VjRwBh0k6vjb54',
    appId: '1:38021008884:web:b3b0fa620d40649c1a7da1',
    messagingSenderId: '38021008884',
    projectId: 'newsappproject-1d9a6',
    authDomain: 'newsappproject-1d9a6.firebaseapp.com',
    storageBucket: 'newsappproject-1d9a6.appspot.com',
    measurementId: 'G-7N7XECTBXL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxdYhfiE94qlc_KEs_mXZMR3yjuycBOGs',
    appId: '1:38021008884:android:fd596272295584941a7da1',
    messagingSenderId: '38021008884',
    projectId: 'newsappproject-1d9a6',
    storageBucket: 'newsappproject-1d9a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHAbJal5eh2rLiA79aLf2tLoRyzCadv0k',
    appId: '1:38021008884:ios:df64dfcf6e936f4e1a7da1',
    messagingSenderId: '38021008884',
    projectId: 'newsappproject-1d9a6',
    storageBucket: 'newsappproject-1d9a6.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHAbJal5eh2rLiA79aLf2tLoRyzCadv0k',
    appId: '1:38021008884:ios:df64dfcf6e936f4e1a7da1',
    messagingSenderId: '38021008884',
    projectId: 'newsappproject-1d9a6',
    storageBucket: 'newsappproject-1d9a6.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvl9Zjv7Io3Yen-M-w9VjRwBh0k6vjb54',
    appId: '1:38021008884:web:f4334ccce7ea01271a7da1',
    messagingSenderId: '38021008884',
    projectId: 'newsappproject-1d9a6',
    authDomain: 'newsappproject-1d9a6.firebaseapp.com',
    storageBucket: 'newsappproject-1d9a6.appspot.com',
    measurementId: 'G-QCHZH8B79Z',
  );
}
